// Code generated by ogen, DO NOT EDIT.

package server

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateRbacResourceOperation     OperationName = "CreateRbacResource"
	GetMeOperation                  OperationName = "GetMe"
	GetProtectedResourceOperation   OperationName = "GetProtectedResource"
	GetRbacResourceOperation        OperationName = "GetRbacResource"
	GetUnprotectedResourceOperation OperationName = "GetUnprotectedResource"
)
