// Code generated by ogen, DO NOT EDIT.

package server

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateRbacResource implements createRbacResource operation.
//
// Create a resource that requires rbac.
//
// POST /rbac
func (UnimplementedHandler) CreateRbacResource(ctx context.Context, req *RbacResource) (r CreateRbacResourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// Get the current user.
//
// GET /me
func (UnimplementedHandler) GetMe(ctx context.Context) (r GetMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProtectedResource implements getProtectedResource operation.
//
// Get a protected resource.
//
// GET /protected
func (UnimplementedHandler) GetProtectedResource(ctx context.Context) (r GetProtectedResourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRbacResource implements getRbacResource operation.
//
// Get a resource that requires rbac.
//
// GET /rbac
func (UnimplementedHandler) GetRbacResource(ctx context.Context) (r GetRbacResourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUnprotectedResource implements getUnprotectedResource operation.
//
// Get an unprotected resource.
//
// GET /unprotected
func (UnimplementedHandler) GetUnprotectedResource(ctx context.Context) (r GetUnprotectedResourceRes, _ error) {
	return r, ht.ErrNotImplemented
}
