// Code generated by ogen, DO NOT EDIT.
package server

type CreateRbacResourceRes interface {
	createRbacResourceRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetProtectedResourceRes interface {
	getProtectedResourceRes()
}

type GetRbacResourceRes interface {
	getRbacResourceRes()
}

type GetUnprotectedResourceRes interface {
	getUnprotectedResourceRes()
}
